export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//PLANT CRUD

export const FETCH_PLANT_START = "FETCH_PLANT_START";
export const FETCH_PLANT_SUCCESS = "FETCH_PLANT_SUCCESS";
export const FETCH_PLANT_FAILURE = "FETCH_PLANT_FAILURE";

export const ADD_PLANT_START = "ADD_PLANT_START";
export const ADD_PLANT_SUCCESS = "ADD_PLANT_SUCCESS";
export const ADD_PLANT_FAILURE = "ADD_PLANT_FAILURE";

export const UPDATE_PLANT_START = "UPDATE_PLANT_START";
export const UPDATE_PLANT_SUCCESS = "UPDATE_PLANT_SUCCESS";
export const UPDATE_PLANT_FAILURE = "UPDATE_PLANT_FAILURE";

export const DELETE_PLANT_START = "FAILURE_PLANT_START";
export const DELETE_PLANT_SUCCESS = "FAILURE_PLANT_SUCCESS";
export const DELETE_PLANT_FAILURE = "FAILURE_PLANT_FAILURE";

//WEEKDAY CRUD
// WEEKDAYs are payload along with PLANTS payload in reducer.js

// ADD_PLANT_START,
// ADD_PLANT_SUCCESS,
// ADD_PLANT_FAILURE

// UPDATE_PLANT_START,
// UPDATE_PLANT_SUCCESS,
// UPDATE_PLANT_FAILURE

// DELETE_PLANT_START,
// DELETE_PLANT_SUCCESS,
// DELETE_PLANT_FAILURE

//
